
language: python

addons:
  firefox: latest

before_install:
  - pip install selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version || exit 1

script:
  - echo "Hello World"
  - ls
  - python scripts/bet_stats.py --username $USERNAME --password $PASSWORD
  
