
language: python

addons:
  firefox: latest

before_install:
  - openssl aes-256-cbc -K $encrypted_e21a95bd5d44_key -iv $encrypted_e21a95bd5d44_iv -in client_secret.json.enc -out client_secret.json -d
  - pip install selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version || exit 1
  - pip install gspread
  - pip install --upgrade oauth2client
  # set up awscli packages
  - pip install awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER

stages:
  - read_bet
  - publish_sheets

jobs:
  include:
    - stage: read_bet
      script:
        - python scripts/bet_stats.py --username $USERNAME --password $PASSWORD
        - cp balance.csv ~/$TRAVIS_BUILD_NUMBER/balance.csv

    - stage: publish_sheets
      if: NOT type IN (pull_request) AND branch = master
      script:
        - cp -t . ~/$TRAVIS_BUILD_NUMBER/balance.csv
        - python scripts/spreadsheet.py --client-secrets ./client_secret.json
      after_success:
        - aws s3 rm --recursive s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER # clean up after ourselves

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
