
language: python

python: 3.6

addons:
  firefox: latest

before_install:
  - openssl aes-256-cbc -K $encrypted_e21a95bd5d44_key -iv $encrypted_e21a95bd5d44_iv -in client_secret.json.enc -out client_secret.json -d
  - pip install selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver --version || exit 1
  - pip install gspread
  - pip install --upgrade oauth2client
  - pip install aenum
  - pip install loguru
  - pip install -r requirements.txt

stages:
  - read_bet
  - publish_sheets

jobs:
  include:
    - stage: read_bet
      script:
        - python3 scripts/query_balance.py --username $USERNAME --password $PASSWORD
      if: NOT branch = master

    - stage: publish_sheets
      if: NOT type IN (pull_request) AND branch = master
      script:
        - python3 scripts/query_balance.py --username $USERNAME --password $PASSWORD --update-spreadsheet True ./client_secret.json
